### ISSUE TITLE
Missing openblas package binary

### ISSUE THREAD

**Issue by plusangel** [darcamo/conan-armadillo#1]
Dear Darlan, 

First of all, thank you for this!

I tried to use directly from your repository in bintray using the attached conanfile.txt
[conanfile.txt](https://github.com/darcamo/conan-armadillo/files/5397413/conanfile.txt) and I got the following error:

```
ERROR: Missing binary: openblas/0.3.10@darcamo/stable:caee15982b731664cfe401624046290536b12c0a
openblas/0.3.10@darcamo/stable: WARN: Can't find a 'openblas/0.3.10@darcamo/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=7, os=Linux
- Options: BUILD_RELAPACK=False, BUILD_WITHOUT_LAPACK=False, DYNAMIC_ARCH=True, DYNAMIC_OLDER=False, USE_THREAD=False, shared=False
- Dependencies: 
- Requirements: 
- Package ID: caee15982b731664cfe401624046290536b12c0a

ERROR: Missing prebuilt package for 'openblas/0.3.10@darcamo/stable'
Try to build from sources with "--build=openblas"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
It might be that I miss something.  Could you help me on that?

**Comment by darcamo** [comment]
Hello @plusangel,

Armadillo depends on the openblas and HDF5 libraries, which I have also created recipes for. These recipes are compiled for some compilers and some versions such that conan can just download the binary for the library as well as the headers. However, this does not include gcc version 7. For instance, run the command below

```bash
conan search "openblas/0.3.10@darcamo/stable" -r darcamo-bintray --table openblas.html
```
where you should replace `darcamo-bintray` by whatever name you choose for my repository. This will create a file called `openblas.html` that you can open in your browser to check for which platform (only Linux in my repository), compiler (including compiler version) and flags there are compiled binaries.

There are two ways you can proceed. One is to pass `--build=openblas` or `--build=missing` to the `conan install` command. This tells conan to compile binaries for each dependency that it has a recipe for but that don't have an already compiled binary for conan to just download. The installation will take more time because openblas will be compiled in your machine.

The other option is to tell conan to use openblas (and optionally HDF5) from your system. More specifically, I have added two options to the armadillo's recipe that you can use for this: `use_system_blas` and `use_system_hdf5`. The default value of both is `False`. If you set to `True` then armadillo's recipe will use BLAS/LAPACK and HDF5 from your system, instead of installing from conan recipes. I have only tested with ubuntu (long time ago) and Arch Linux (the one that I use). When these options are set to `True` conan will ask you the administrative password in order to run the package manager (either apt in case of ubuntu or pacman in case of Arch) to install BLAS, Lapack and HDF5. You can set them in your conanfile.txt as 

```
[requires]
armadillo/10.1.0@darcamo/stable

[options]
armadillo:use_system_blas=True
armadillo:use_system_hdf5=True

[generators]
cmake
```

You can also pass these options directly in the command line with the `conan install` command as `-o armadillo:use_system_blas=True`

-----

Since this issue is not a problem with the recipe I'll close the issue. In case you go with the "armadillo:use_system_[blas | hdf5] = True" approach and you don't use either ubuntu or Arch, it will fail. Pull requests are welcomed. All that is necessary is the value returned by `conans.tools.os_info.linux_distro` (in Python) and the name of the blas, lapack and hdf5 libraries in your distro.

**Comment by plusangel** [comment]
Firstly, thank for you time to write a detailed reply indicating and explaining all the possibilities to a newbie. Secondly, it worked like a charm. Great!
